language: node_js
node_js:
- 4.3.2
sudo: required
dist: trusty
cache:
  directories: node_modules
before_script:
- npm install -g gulp
script: gulp test
after_success: gulp dist
deploy:
  provider: lambda
  skip_cleanup: true
  edge: true
  access_key_id:
    secure: QGcEutdKFVQ9UJaEQ+G4jmssT7TFGMkllv5HXEpWyzoRPA6xywU25sUpYTgUENxYkuw0pryB01OYBlDn+ngPyHj9SX2cUOt9P5ckvO8hD8MOWrQgEbarvm05GsRS8O8DcR5FB1zgba419LFDcdUTKJMxkONXdI5X7DPSRafd8xqN+FxMH6fOWHu+Y4XhNq6GTD53js9gUnUaKWWJw80iLvAmWL/UOT+BWrhVt/p38Ylxx+UzDYY3hqRpV94uxotLy3oEPdZcr1R2OzJsDyPW59It22/j3F0m7h019W9dmw3Mm/x4mb5i/Vb7eCmveStU/gk+uy1q1+2ofc7roL6G73Eo9aTfjZERUsRL5QNDkC5Sqm2h0cjqvdKDVlmjd8fGbgHkGZzq7UpygY3AVRE2esd6x3CuQxNa6EjEhhMzGHxvgumisUIzlK6kf4zh2xvTxDj4iKqKNGdAw3aUI/jIBKEQM89Jn2ZMJTBqlRq53WijG9fq/spJiCM+eBouO4rfunGUSZLIiYNzlbCsjmn/LEPlZ42UpSThrzozAKtaEK27GxlrJ0xItqp2/VuVm6U7XJDOBtOA9M8zKW0s7VIfzTBe0qmrS9h8UBRIveDEDlmIq24/6xDQBVMXEyZ96yW7N0G9LSCIg44lQd5FOw40hO6fvwJaqTEs5MAltd03OrE=
  secret_access_key:
    secure: ZJA0kopKA6gqJbG5qwj487pK2vFn0CHwd31yc9ZbaRqYQVod8uNkyFoXXgvOhW0LO0ddfcJITtNz5Ofj4sDeq87SUf4WcTanHs0fSEjBrPvZBfo/wtCK80XblttdKXo/ITZTmFfYvtA5TtE9xXqmzQGnE3NGyH7oMnRleYW/88AuRCSt0gqHN+qYF3tYbWHnVSULji0iphqJ5NQHTt3KSltRVAR8Q2ImbaPGal28jGcwwx3T443gP/HITqKqp61zKv2SXh8zN35OX4G3ng0G6qGUVWpMkRYJWKQls1VOXAPnSqJ79BwsRTpTmp1h8q2bl/76LmR3YWoI90vPbLem+BmvrQoiNRYo6kVNEJkhA12KGgbDmTXFS+b+7QfmWLMDBlCk6Qp72eHn5Htt139ZD9zC4aDCCATulpmEjbzuFJ11iCqsy6iDmyDkL3oeYajN0CySct28KAYw75B0HhhaRaB+n75bNZARFkGwB5npXkOINoD0/5E0316WP/wJFlNAEBAVfkMFIcRQRb/082SMoTN5M/oCfl74rW66UrCJVIeqG27BcSz86u5tzNBPjUG72vp6wwfBHWEzuXrw2l9zqHDNhxnx8wD4Giqgy3jtqsS2Ql+CbcSoaMaHDa3E5ifDPmfV8eqkkxCc9LKdFcGridTjjuv88H8BUtLRFeUY5Kg=
  function_name: recommerce-auth
  handler_name: handler
  runtime: nodejs4.3
  role:
    secure: BEleMklBu72OC7ZV/DtZtJp+ALd9vhmA95T3kh/cGt6auvt/32VC2Rz8yQveW1eK/5bsHyg0ooja0BnCKrtLsMTb0R9Xhs1k87HFzOYQzltmlvxPgpmcPcpEekxh4V7MQpwxUPeTw9wcC5nDz+pgXz6QXKBPZ8ew4h9HOPkCp1a0txjPk+haOzJBLR0Sse2g+Atn4Zk6bndLPwKbWIYzInFAdIx3pBeW/+ZmZklJzt19runA0lh/zkBiKgoKIReJVDirjj39M2pZrO0683Ou7D5SpEA+5FoIDsSIvu0TQPwBLYsQnxd6tn7MeJrIm/jqsYhwLVV+12+urzK+yIWgJuT3npAI7pj2TvxOaaTcq9WHto1PQc/kZ11sxdya6IwDWgIghqe5SxE/w6sLohdNML0qiVbNakixdTsGqCww0Z1emu716Ox75NgQaqv4MuhVm57iDTTz4swX7XstBcRRyGaYBzNEvmZQYtP6IVrQ479mlMNJ4+ODNti1yBJ+qU3IbGul6CuDiA3Ta8cL154iQRpbnDZuB+LPkCVNtVZjXHef5O+gmughX8USoDCIjcZv1MNhdf7IaC7HlQnC8YZySb5gqyBXMOHLN7QXXu9mX+3EA7T+7iLCB+YCJ63mYFbE7DC9Uff++5k1LKBnC8NCr0/DqeFBJsEKWvTzvtcsHRc=
  zip_file: dist.zip
before_install:
- openssl aes-256-cbc -K $encrypted_68c26b5cefa4_key -iv $encrypted_68c26b5cefa4_iv
  -in recommerce-secret.json.enc -out recommerce-secret.json -d
